setup: |
  echo "Done installing project dependencies!"
---

# Reminder for ^^^:
# All commands executed in the setup block are done in a
# one-by-one fashion from the current working directory. This means
# that there is no history associated with running the commands and
# thus multiple commands must be run in a single chain.

# perform checks on a file
- README.md:
    - description: Ensure that the README.md file exists
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers in README.md
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true

- index.md:
    - description: Ensure that the index.md file exists
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers in index.md
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: include heading for Reviews in index.md
      check: MatchFileFragment
      options:
        fragment: "# Reviews"
        count: 1
        exact: false
    - description: include quotes under the reviews using Markdown syntax (in index.md)
      check: MatchFileFragment
      options:
        fragment: ">"
        count: 2
        exact: false

- _config.yml:
    - description: Ensure that the _config.yml file exists
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers in _config.yml
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true

- menu.md:
    - description: Ensure that the menu.md file exists
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers in menu.md
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: include at least one menu item photo in menu.md
      check: MatchFileFragment
      options:
        fragment: "]("
        count: 1
        exact: false
    - description: remove the default image in menu.md
      check: MatchFileFragment
      options:
        fragment: "magnifying-glass-logo.jpeg"
        count: 0
        exact: true

- contact.md:
    - description: Ensure that the contact.md file exists
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers in contact.md
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: include at least one heading in contact.md
      check: MatchFileFragment
      options:
        fragment: "# Hours"
        count: 1
        exact: true

- _explorations/review1.md:
    - description: Ensure that the _explorations/review1.md file exists
      check: ConfirmFileExists
    - description: Write minimum of 150 words in _explorations/review1.md
      check: CountFileWords
      options:
        count: 150
        exact: false
    - description: include link in markdown to the site that you reviewed in review1.md
      check: MatchFileFragment
      options:
        fragment: "]("
        count: 1
        exact: false

- _explorations/review2.md:
    - description: Ensure that the _explorations/review2.md file exists
      check: ConfirmFileExists
    - description: Write minimum of 150 words in _explorations/review2.md
      check: CountFileWords
      options:
        count: 150
        exact: false
    - description: include link in markdown to the site that you reviewed in review2.md
      check: MatchFileFragment
      options:
        fragment: "]("
        count: 1
        exact: false

- _explorations/analytics.md:
    - description: Ensure that the _explorations/analytics.md file exists
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers in analytics.md
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: Write minimum of 150 words in _explorations/analytics.md
      check: CountFileWords
      options:
        count: 150
        exact: false
    - description: include at least 1 image from assets/images in analytics.md
      check: MatchFileFragment
      options:
        fragment: assets/images
        count: 1
        exact: false

# count number of commits in the GitHub repository
- description: Have a total of at least 9 local commits in repository
  check: CountCommits
  options:
    count: 9